const CLIENT_STATUS = {
  NEW: 'NEW',
  EXISTING: 'EXISTING',
  DUPLICATE: 'DUPLICATE',
  ERROR: 'ERROR'
};

const PROFILE_STATUS = {
  COMPLETE: 'COMPLETE',
  PARTIAL: 'PARTIAL',
  INCOMPLETE: 'INCOMPLETE'
};

module.exports = {
  CLIENT_STATUS,
  PROFILE_STATUS
};
