const CLOSING_STRATEGY = {
  CLOSE_NEW_CLIENT_SOFT: 'CLOSE_NEW_CLIENT_SOFT',
  CLOSE_SERVICE_TO_COMBO_UPGRADE: 'CLOSE_SERVICE_TO_COMBO_UPGRADE',
  CLOSE_EXISTING_CLIENT_FAST_TRACK: 'CLOSE_EXISTING_CLIENT_FAST_TRACK',
  CLOSE_BIRTHDATE_ENRICHMENT_SOFT: 'CLOSE_BIRTHDATE_ENRICHMENT_SOFT',
  CLOSE_MANUAL_REVIEW_SAFE: 'CLOSE_MANUAL_REVIEW_SAFE',
  CLOSE_REACTIVATION_SOFT: 'CLOSE_REACTIVATION_SOFT'
};

module.exports = {
  CLOSING_STRATEGY
};
