const ERROR_CODE = {
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  GOOGLE_SHEETS_LOOKUP_FAILED: 'GOOGLE_SHEETS_LOOKUP_FAILED',
  CLIENT_PERSISTENCE_FAILED: 'CLIENT_PERSISTENCE_FAILED'
};

module.exports = {
  ERROR_CODE
};
