const SALES_ROUTE = {
  ROUTE_NEW_ONBOARDING: 'ROUTE_NEW_ONBOARDING',
  ROUTE_EXISTING_PROFILE_COMPLETION: 'ROUTE_EXISTING_PROFILE_COMPLETION',
  ROUTE_EXISTING_DIRECT_SALE: 'ROUTE_EXISTING_DIRECT_SALE',
  ROUTE_DUPLICATE_SAFE_FALLBACK: 'ROUTE_DUPLICATE_SAFE_FALLBACK',
  ROUTE_TECHNICAL_FALLBACK: 'ROUTE_TECHNICAL_FALLBACK',
  ROUTE_INVALID_PHONE_FALLBACK: 'ROUTE_INVALID_PHONE_FALLBACK',
  ROUTE_OUT_OF_COVERAGE: 'ROUTE_OUT_OF_COVERAGE'
};

module.exports = {
  SALES_ROUTE
};
